Repository KoushikMallik-developer/split-it-api-v2, pull requests merged in 2025-01, with the labels that each got.

#30 24 handle exceptions
  auth_api/auth_exceptions/user_exceptions.py
  auth_api/export_types/email_types/auth_email.py
  auth_api/export_types/request_data_types/change_password.py
  auth_api/export_types/request_data_types/create_user.py
  auth_api/export_types/request_data_types/sign_in.py
  auth_api/export_types/request_data_types/verify_otp.py
  auth_api/models/user_models/user.py
  auth_api/serializers/user_serializer.py
  auth_api/services/handlers/exception_handlers.py
  auth_api/services/helpers.py
  auth_api/services/user_services/user_services.py
  auth_api/tests/handlers/__init__.py
  auth_api/tests/handlers/test_exception_handlers.py
  auth_api/tests/views/__init__.py
  auth_api/tests/views/conftest.py
  auth_api/tests/views/test_all_users.py
  auth_api/tests/views/test_create_users.py
  auth_api/tests/views/test_remove_user.py
  auth_api/tests/views/test_reset_password.py
  auth_api/tests/views/test_send_otp.py
  auth_api/tests/views/test_sign_in.py
  auth_api/tests/views/test_update_password.py
  auth_api/tests/views/test_update_profile.py
  auth_api/tests/views/test_user_details.py
  auth_api/tests/views/test_verify_otp.py
  auth_api/views/all_users.py
  auth_api/views/create_user.py
  auth_api/views/otp_view.py
  auth_api/views/password_reset.py
  auth_api/views/remove_user.py
  auth_api/views/sign_in.py
  auth_api/views/update_password.py
  auth_api/views/update_profile.py
  auth_api/views/user_details.py
  auth_api/views/validate_otp_view.py
Labels: enhancement

#46 added gunicorn
  requirements.txt
Labels: bug

#50 added refresh access token feature
  auth_api/tests/views/test_refresh_token.py
  auth_api/urls.py
  auth_api/views/refresh_token.py
Labels: required immediate action

#55 Restructured code
  .github/workflows/ci.yml
  .gitignore
  auth_api/export_types/request_data_types/search_user.py
  auth_api/export_types/user_types/export_user.py
  auth_api/migrations/0001_initial.py
  auth_api/migrations/0002_useremailverification.py
  auth_api/models/user_models/user.py
  auth_api/services/handlers/exception_handlers.py
  auth_api/services/token_services/token_generator.py
  auth_api/services/user_services/user_services.py
  auth_api/views/refresh_token.py
  auth_api/views/search_user.py
  friends/admin.py
  friends/export_types/friend_types/export_friend.py
  friends/migrations/0001_initial.py
  friends/migrations/0002_alter_friend_user1_alter_friend_user2_and_more.py
  friends/models/friend.py
  friends/serializers/accept_friend_request_serializer.py
  friends/serializers/friend_request_serializer.py
  friends/serializers/remove_friend_request_serializer.py
  friends/serializers/remove_friend_serializer.py
  friends/services/friends_services.py
  friends/views/accept_friend_request.py
  friends/views/add_friend.py
  friends/views/all_friend_requests.py
  friends/views/all_friends.py
  friends/views/my_received_friend_requests.py
  friends/views/my_sent_friend_requests.py
  friends/views/remove_friend.py
  friends/views/remove_friend_request.py
  friends/views/search_friend.py
  groups/export_types/group_types/__init__.py
  groups/export_types/group_types/export_group.py
  groups/export_types/request_data_type/__init__.py
  groups/export_types/request_data_type/add_member.py
  groups/export_types/request_data_type/create_group.py
  groups/export_types/request_data_type/update_group.py
  groups/group_exceptions/group_exceptions.py
  groups/migrations/0001_initial.py
  groups/models/group.py
  groups/serializers/add_member_serializer.py
  groups/serializers/group_serializer.py
  groups/services/group_services.py
  groups/view/add_members.py
  groups/view/create_group.py
  groups/view/update_group.py
Labels: required immediate action

#66 fixed bugs
  auth_api/export_types/user_types/export_user.py
  auth_api/services/helpers.py
  auth_api/tests/views/test_all_users.py
  auth_api/tests/views/test_user_details.py
Labels: bug

#68 added create expense
  auth_api/export_types/user_types/export_user.py
  auth_api/models/user_models/user.py
  e_app/admin.py
  e_app/expense_exceptions/__init__.py
  e_app/expense_exceptions/expense_exceptions.py
  e_app/export_types/__init__.py
  e_app/export_types/export_expense_types/__init__.py
  e_app/export_types/export_expense_types/export_expense.py
  e_app/export_types/request_data_types/__init__.py
  e_app/export_types/request_data_types/add_expense_request_type.py
  e_app/models/balance.py
  e_app/models/expense.py
  e_app/models/user_balance.py
  e_app/serializers/__init__.py
  e_app/serializers/expense_serializer.py
  e_app/services/__init__.py
  e_app/services/balance_services.py
  e_app/services/expense_services.py
  e_app/urls.py
  e_app/views.py
  e_app/views/__init__.py
  e_app/views/add_expense.py
  groups/export_types/group_types/export_group.py
  groups/export_types/request_data_type/add_member.py
  groups/serializers/add_member_serializer.py
  groups/services/group_services.py
Labels: enhancement

#72 fixed add friend
  friends/export_types/request_data_types/add_friend.py
  friends/serializers/friend_request_serializer.py
  friends/services/friends_services.py
Labels: bug

#73 bug fix search user
  auth_api/services/user_services/user_services.py
  auth_api/views/search_user.py
Labels: bug

#75 74 bug fix friends api
  auth_api/services/handlers/exception_handlers.py
  auth_api/services/helpers.py
  friends/export_types/request_data_types/accept_friend_requeset.py
  friends/export_types/request_data_types/remove_friend.py
  friends/export_types/request_data_types/remove_friend_requeset.py
  friends/serializers/accept_friend_request_serializer.py
  friends/serializers/friend_request_serializer.py
  friends/serializers/remove_friend_request_serializer.py
  friends/serializers/remove_friend_serializer.py
  friends/services/friends_services.py
  friends/views/add_friend.py
  friends/views/remove_friend_request.py
Labels: bug

#77 search user modification
  auth_api/export_types/user_types/export_user.py
  auth_api/services/user_services/user_services.py
  auth_api/views/search_user.py
Labels: bug, enhancement

#79 removed self user from user search
  auth_api/services/user_services/user_services.py
  auth_api/views/search_user.py
Labels: bug

#80 fixed friend request accept
  friends/services/friends_services.py
Labels: bug

#83 bug fix in friend request
  friends/export_types/friend_types/export_friend_requests.py
Labels: bug

#84 new endpoint to fetch any user info
  auth_api/urls.py
  auth_api/views/fetch_user.py
Labels: enhancement

#87 fixed fetch user details by id
  auth_api/services/user_services/user_services.py
  auth_api/views/fetch_user.py
Labels: bug

#89 88 bug fix group and friend
  friends/serializers/remove_friend_serializer.py
  groups/serializers/group_serializer.py
  groups/urls.py
Labels: bug
